# -*- coding: utf-8 -*-
"""Final Poject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpY5VD1e65_pu_WCODpY0d0tQKxiGm2M
"""

# Import necessary libraries for data manipulation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**Data Loading & Basic Exploration**"""

# Load the dataset from CSV file into a pandas DataFrame
df = pd.read_csv('hotel_booking.csv')

# Display the first five rows of the dataset to inspect the structure
df.head()

# Display the last five rows of the dataset
df.tail()

# Check the total number of rows and columns in the dataset
df.shape

# Check column names, data types, and non-null values
df.info()

# Generate summary statistics for numerical columns to spot anomalies
df.describe()

"""**Data Cleaning & Preprocessing**"""

# Check the total count of duplicated rows across the dataset
df.duplicated().sum()

# Check the count of missing values in each column
df.isnull().sum()

# Drop the 'company' column due to an overwhelming percentage of missing values
df = df.drop(columns=['company'])

# Impute missing values in 'agent' with 0 to indicate bookings made without an agent
df['agent'] = df['agent'].fillna(0)

# Replace missing country values with 'Unknown' to preserve data integrity
df['country'] = df['country'].fillna('Unknown')

# Verify that all missing values have been successfully handled
df.isnull().sum().sum()

# Identify the exact column containing the remaining 4 missing values
df.columns[df.isnull().any()].tolist()

# Fill the 4 missing values in 'children' with 0 assuming no children were present
df['children'] = df['children'].fillna(0)

# Confirm that zero missing values remain in the entire dataset
df.isnull().sum().sum()

# Drop unnecessary personal identification columns generated for synthetic purposes
df = df.drop(columns=['name', 'email', 'phone-number', 'credit_card'], errors='ignore')

# Convert 'children' and 'agent' data types from float to integer for consistency
df[['children', 'agent']] = df[['children', 'agent']].astype(int)

# Convert reservation status date from string object to datetime format
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

# Check how many rows have zero guests (adults, children, and babies are all zero)
((df['adults'] == 0) & (df['children'] == 0) & (df['babies'] == 0)).sum()

# Drop rows where there are zero total guests (adults + children + babies > 0)
df = df[(df['adults'] + df['children'] + df['babies']) > 0]

# Inspect the minimum and maximum values of ADR to detect extreme outliers
df['adr'].describe()[['min', 'max']]

# Filter out invalid negative prices and extreme outliers in ADR
df = df[(df['adr'] > 0) & (df['adr'] < 5000)]

# Reset row index after filtering to maintain continuous numbering
df = df.reset_index(drop=True)

# Check the final shape of the cleaned dataframe
df.shape

"""**Feature Engineering**"""

# Create total stay duration by combining weekend nights and week nights
df['total_stay'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

# Create total guests count by summing adults, children, and babies
df['total_guests'] = df['adults'] + df['children'] + df['babies']

# Extract year and month from the reservation status date for seasonal analysis
df['reservation_year'] = df['reservation_status_date'].dt.year
df['reservation_month'] = df['reservation_status_date'].dt.month

# Create a flag indicating whether the assigned room differs from the reserved room
df['room_type_changed'] = (df['reserved_room_type'] != df['assigned_room_type']).astype(int)

# Save the cleaned and engineered dataset to a new CSV file
df.to_csv('hotel_bookings_cleaned.csv', index=False)

"""**Exploratory Data Analysis (EDA) & Insights**"""

# PLOT 1: Overall Booking Cancellation Rate
# PURPOSE: Understand the baseline cancellation rate across all reservations to
#          evaluate the magnitude of lost revenue and operational impact.


plt.figure(figsize=(7, 5))
ax = sns.countplot(data=df, x='is_canceled', palette=['#2b5c8f', '#d95f02'])

# Add percentage labels above bars
total = len(df)
for p in ax.patches:
    percentage = f'{100 * p.get_height() / total:.1f}%'
    ax.annotate(percentage, (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=11, fontweight='bold', xytext=(0, 5),
                textcoords='offset points')

plt.title('Overall Reservation Status (0 = Not Canceled, 1 = Canceled)', fontsize=13)
plt.xlabel('Booking Status', fontsize=11)
plt.ylabel('Total Bookings', fontsize=11)
plt.xticks(ticks=[0, 1], labels=['Not Canceled', 'Canceled'])
plt.show()

"""### Key Insight - Overall Cancellations:
* Approximately **37%** of all bookings were canceled, representing a substantial loss of potential revenue.
* The baseline cancellation rate indicates a critical need to understand the underlying drivers (e.g., lead time, hotel type, pricing policies).

"""

# PLOT 2: Cancellation Comparison by Hotel Type
# PURPOSE: Identify whether cancellation behavior differs significantly between
#          City Hotel and Resort Hotel to tailor operational strategies.


plt.figure(figsize=(8, 5))
ax = sns.countplot(data=df, x='hotel', hue='is_canceled', palette=['#2b5c8f', '#d95f02'])

plt.title('Booking Cancellations by Hotel Type', fontsize=13)
plt.xlabel('Hotel Type', fontsize=11)
plt.ylabel('Number of Bookings', fontsize=11)
plt.legend(title='Status', labels=['Not Canceled', 'Canceled'])
plt.show()

"""### Key Insight - Cancellations by Hotel Type:
* **City Hotel** experiences significantly higher cancellation volumes and rates compared to **Resort Hotel**.
* **Actionable Takeaway:** City hotels likely suffer from flexible business travel changes or competitive urban alternatives; introducing non-refundable deposit policies could mitigate this risk.
*
"""

# PLOT 3: Lead Time vs. Cancellation Status
# PURPOSE: Determine if the advance booking window (lead time) correlates with
#          higher cancellation likelihood.


plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='is_canceled', y='lead_time', palette=['#2b5c8f', '#d95f02'], showfliers=False)

plt.title('Lead Time Distribution by Cancellation Status', fontsize=13)
plt.xlabel('Booking Status', fontsize=11)
plt.ylabel('Lead Time (Days)', fontsize=11)
plt.xticks(ticks=[0, 1], labels=['Not Canceled', 'Canceled'])
plt.show()

"""### Key Insight - Lead Time vs. Cancellation:
* Bookings with longer **lead times** have a significantly higher tendency to be canceled; the median lead time for canceled bookings is over 100 days compared to under 50 days for completed stays.
* **Actionable Takeaway:** Implement stricter cancellation policies or reminders with special incentives for bookings made several months in advance.

"""

# PLOT 4: Monthly Booking and Cancellation Trends
# PURPOSE: Identify seasonal patterns and peak cancellation periods throughout
# the year to optimize seasonal staffing and dynamic pricing.


monthly_trends = df.groupby(['arrival_date_month', 'is_canceled']).size().reset_index(name='count')

# Order months chronologically
months_order = ['January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December']
monthly_trends['arrival_date_month'] = pd.Categorical(monthly_trends['arrival_date_month'], categories=months_order, ordered=True)
monthly_trends = monthly_trends.sort_values('arrival_date_month')

plt.figure(figsize=(12, 5))
sns.lineplot(data=monthly_trends, x='arrival_date_month', y='count', hue='is_canceled',
             marker='o', palette=['#2b5c8f', '#d95f02'], linewidth=2.5)

plt.title('Monthly Booking Trends: Completed vs Canceled', fontsize=13)
plt.xlabel('Arrival Month', fontsize=11)
plt.ylabel('Number of Bookings', fontsize=11)
plt.xticks(rotation=45)
plt.legend(title='Status', labels=['Not Canceled', 'Canceled'])
plt.tight_layout()
plt.show()

"""### Key Insight - Seasonality Trends:
* **Peak Season:** August and July experience the highest volume of total bookings, as well as the highest cancellation counts, coinciding with summer holiday travel.
* **Low Season:** Winter months (November to January) show the lowest reservation and cancellation volumes.
* **Actionable Takeaway:** Implement dynamic overbooking strategies and stricter pre-payment policies during July and August to protect against high-volume summer cancellations.

"""

# PLOT 5: Average Daily Rate (ADR) vs. Cancellation Status
# PURPOSE: Assess whether higher room rates increase the probability of booking
# cancellations to guide pricing optimization.


plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='is_canceled', y='adr', palette=['#2b5c8f', '#d95f02'], showfliers=False)

plt.title('Average Daily Rate (ADR) by Cancellation Status', fontsize=13)
plt.xlabel('Booking Status', fontsize=11)
plt.ylabel('Average Daily Rate (ADR)', fontsize=11)
plt.xticks(ticks=[0, 1], labels=['Not Canceled', 'Canceled'])
plt.show()

"""### Key Insight - Room Price (ADR) vs. Cancellation:
* Canceled bookings exhibit a slightly higher median and upper quartile Average Daily Rate (ADR) compared to completed bookings.
* Higher room rates appear to drive comparison shopping, leading customers to cancel if more affordable alternatives are found closer to the stay date.

"""

# PLOT 6: Impact of Room Assignment Changes on Cancellations
# PURPOSE: Evaluate whether assigning a different room than reserved triggers
# higher customer dissatisfaction and cancellations.


plt.figure(figsize=(7, 5))
ax = sns.barplot(data=df, x='room_type_changed', y='is_canceled', ci=None, palette=['#2b5c8f', '#d95f02'])

# Add percentage labels above bars
for p in ax.patches:
    percentage = f'{100 * p.get_height():.1f}%'
    ax.annotate(percentage, (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=11, fontweight='bold', xytext=(0, 5),
                textcoords='offset points')

plt.title('Cancellation Rate by Room Change Status', fontsize=13)
plt.xlabel('Room Type Changed (0 = Same Room, 1 = Changed Room)', fontsize=11)
plt.ylabel('Cancellation Rate', fontsize=11)
plt.xticks(ticks=[0, 1], labels=['Same Room', 'Changed Room'])
plt.ylim(0, 0.5)
plt.show()

"""### Key Insight - Room Type Change vs. Cancellation:
* Bookings where the assigned room differed from the reserved room had a remarkably low cancellation rate (**5.5%**) compared to **41.9%** for those with unchanged rooms.
* **Interpretation:** Room reassignments often represent complimentary upgrades provided at check-in, enhancing guest satisfaction and virtually eliminating last-minute cancellations.

"""

# PLOT 7: Cancellations by Market Segment
# PURPOSE: Identify which booking channels (e.g., Online Travel Agencies, Direct)
#  generate the highest cancellation risk.


plt.figure(figsize=(10, 5))
ax = sns.countplot(data=df, x='market_segment', hue='is_canceled', palette=['#2b5c8f', '#d95f02'],
                  order=df['market_segment'].value_counts().index)

plt.title('Booking Cancellations by Market Segment', fontsize=13)
plt.xlabel('Market Segment', fontsize=11)
plt.ylabel('Number of Bookings', fontsize=11)
plt.xticks(rotation=30)
plt.legend(title='Status', labels=['Not Canceled', 'Canceled'])
plt.tight_layout()
plt.show()

"""### Key Insight - Cancellations by Market Segment:
* **Online Travel Agencies (Online TA):** Account for the largest volume of bookings and cancellations, driven by flexible and hassle-free cancellation policies.
* **Groups:** Show an alarming trend where canceled bookings exceed completed ones, indicating high volatility in mass reservations.
* **Direct & Corporate:** Exhibit significantly lower cancellation rates, representing more reliable revenue streams.
* **Actionable Takeaway:** Require stricter non-refundable deposits for group bookings and introduce loyalty incentives for direct bookings to reduce reliance on volatile online channels.

"""

# PLOT 8: Correlation Heatmap of Numerical Features
# PURPOSE: Summarize linear relationships between key numerical variables and
# cancellations to validate EDA hypotheses in a single visual.


# Select key numerical columns for a clear and readable heatmap
numerical_cols = ['is_canceled', 'lead_time', 'total_stay', 'total_guests',
                  'adr', 'previous_cancellations', 'booking_changes', 'room_type_changed']

plt.figure(figsize=(10, 8))
corr_matrix = df[numerical_cols].corr()

sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', vmin=-1, vmax=1,
            square=True, linewidths=0.5, cbar_kws={'shrink': 0.8})

plt.title('Correlation Matrix of Key Numerical Features', fontsize=13)
plt.tight_layout()
plt.show()

"""### Key Insight - Correlation Analysis:
* **Lead Time (+0.29):** Shows the strongest positive correlation with cancellations, confirming that advance booking windows are the primary operational risk.
* **Room Type Changed (-0.24):** Exhibits the strongest negative correlation, reinforcing that complimentary upgrades and room adjustments at check-in drastically secure guest arrival.
* **Booking Changes (-0.14):** Active reservation modifications signal committed guests, lowering cancellation likelihood.

## Final Business Recommendations & Action Plan

Based on the Exploratory Data Analysis (EDA), the following data-driven strategies are recommended to mitigate cancellation risks and optimize hotel operations:

1. **Dynamic Deposit Policies for Long Lead Times:**
   * Require non-refundable deposits or full upfront payment for reservations booked more than **60–90 days in advance**.
   * Send automated engagement reminders and exclusive early-check-in incentives to maintain commitment.

2. **Mitigating City Hotel & Group Cancellation Volatility:**
   * City hotels and group bookings exhibit disproportionately high cancellation rates. Enforce stricter group cancellation windows (e.g., 30-day non-refundable policy).
   * Incentivize corporate partners and frequent travelers with loyalty perks to encourage direct bookings over volatile online channels.

3. **Capitalizing on Peak Summer Demand (July & August):**
   * High demand in peak summer months leads to peak cancellation volumes. Implement controlled overbooking models based on historical summer cancellation rates to protect occupancy.
   * Offer discounted, fully non-refundable summer packages to lock in revenue early.

4. **Leveraging Complimentary Room Upgrades:**
   * Room reassignments yield a near-zero cancellation rate (5.5%). Standardize complimentary upgrades at check-in when lower-tier rooms are overbooked to enhance guest satisfaction and secure completed stays.
"""