USE [Hotel Booking];
GO


--------------------------------------------------
-- 1. TOP 10 COUNTRIES BY REVENUE
-- Identify the countries generating the highest revenue
--------------------------------------------------
SELECT TOP 10
    country,
    COUNT(*) AS total_bookings,
    ROUND(SUM(  adr * (stays_in_weekend_nights + stays_in_week_nights) ), 2) AS total_revenue,
    ROUND(AVG(adr), 2) AS avg_adr
FROM dbo.[hotel_bookings_cleaned.csv]
WHERE is_canceled = 0
GROUP BY country
ORDER BY total_revenue DESC;


--------------------------------------------------
-- 2. REVENUE BY MARKET SEGMENT
-- Identify the market segments generating the highest revenue
--------------------------------------------------
SELECT
    market_segment,
    COUNT(*) AS total_bookings,
    ROUND(SUM( adr * (stays_in_weekend_nights + stays_in_week_nights) ), 2) AS total_revenue,
    ROUND(AVG(adr), 2) AS avg_adr
FROM dbo.[hotel_bookings_cleaned.csv]
WHERE is_canceled = 0
GROUP BY market_segment
ORDER BY total_revenue DESC;


--------------------------------------------------
-- 3. MARKET SEGMENT BOOKING SHARE
-- Measure the percentage of bookings generated by each segment
--------------------------------------------------
SELECT
    market_segment,
    COUNT(*) AS total_bookings,
    CAST(COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER () AS DECIMAL(10,2)
       ) AS booking_share_pct
FROM dbo.[hotel_bookings_cleaned.csv]
GROUP BY market_segment
ORDER BY booking_share_pct DESC;


--------------------------------------------------
-- 4. CANCELLATION RATE BY DISTRIBUTION CHANNEL
-- Compare cancellation rates across distribution channels
--------------------------------------------------
SELECT
    distribution_channel,
    COUNT(*) AS total_bookings,
    SUM(
        CASE
            WHEN is_canceled = 1 THEN 1
            ELSE 0
        END
    ) AS canceled_bookings,
    CAST(SUM(
            CASE
                WHEN is_canceled = 1 THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*) AS DECIMAL(10,2)) AS cancellation_rate_pct
FROM dbo.[hotel_bookings_cleaned.csv]
GROUP BY distribution_channel
ORDER BY cancellation_rate_pct DESC;

--------------------------------------------------
-- 5. TOP 10 AGENTS BY CONFIRMED BOOKINGS
-- Identify the agents generating the most confirmed bookings
--------------------------------------------------
SELECT TOP 10
    agent,
    COUNT(*) AS successful_bookings,
    ROUND( SUM( adr * (stays_in_weekend_nights + stays_in_week_nights)), 2 ) AS total_revenue,
    ROUND(AVG(adr), 2) AS avg_adr
FROM dbo.[hotel_bookings_cleaned.csv]
WHERE is_canceled = 0
  AND agent <> 0
GROUP BY agent
ORDER BY successful_bookings DESC;


--------------------------------------------------
-- 6. TOP 10 AGENTS BY REVENUE
-- Identify the agents generating the highest revenue
--------------------------------------------------
SELECT TOP 10
    agent,
    COUNT(*) AS successful_bookings,
    ROUND(SUM( adr * (stays_in_weekend_nights + stays_in_week_nights)), 2) AS total_revenue,
    ROUND(AVG(adr), 2) AS avg_adr
FROM dbo.[hotel_bookings_cleaned.csv]
WHERE is_canceled = 0
  AND agent <> 0
GROUP BY agent
ORDER BY total_revenue DESC;


--------------------------------------------------
-- 7. REPEAT GUESTS BY MARKET SEGMENT
-- Identify which marketing segments attract repeat guests
--------------------------------------------------
SELECT
    market_segment,
    COUNT(*) AS repeated_guests,
    ROUND( SUM(adr * (stays_in_weekend_nights + stays_in_week_nights)), 2) AS repeated_guest_revenue,
    ROUND(AVG(adr), 2) AS avg_adr
FROM dbo.[hotel_bookings_cleaned.csv]
WHERE is_repeated_guest = 1
  AND is_canceled = 0
GROUP BY market_segment
ORDER BY repeated_guests DESC;


--------------------------------------------------
-- 8. AVERAGE LEAD TIME BY MARKET SEGMENT
-- Analyze customer booking behavior across marketing segments
--------------------------------------------------

SELECT
    market_segment,
    COUNT(*) AS total_bookings,
    ROUND(AVG(CAST(lead_time AS FLOAT)),2) AS avg_lead_time_days,
    ROUND(AVG(CAST(adr AS FLOAT)),2) AS avg_ad
FROM dbo.[hotel_bookings_cleaned.csv]
GROUP BY market_segment
ORDER BY avg_lead_time_days DESC;